export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const INCREMENT_ORDER_ITEM = 'INCREMENT_ORDER_ITEM';
export const DECREMENT_ORDER_ITEM = 'DECREMENT_ORDER_ITEM';
export const TO_CLOSE_ORDER = 'TO_CLOSE_ORDER';
